### ISSUE TITLE
`SeasonCountdownSectionBackground`: width update delay issue

### ISSUE THREAD

**Issue by kpyszkowski** [thesis/acre#383]
There is a slight delay of width recalculation when the background SVG element is resized.
Very first investigation led me to conclusion it's browser specific and we don't have anything to do with it. The code itself doesn't have any sort of delay or transition applied and is quite performant.

https://github.com/thesis/acre/assets/11503879/ed0f2039-a34d-4752-8195-782b3b9671c8

**Comment by kkosiorowska** [comment]
The issue is outdated.
