### ISSUE TITLE
dApp: Display the total number of users and TVL

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#444]
Currently, the dApp does not display the total number of users and TVL. What should be done:

- [ ] Fetch the necessary information from the SDK.
- [ ] Display the required data when the total number of users is greater than 500.

![Screenshot 2024-06-04 at 14 55 21](https://github.com/thesis/acre/assets/23117945/7c00380f-a174-4864-b5a9-ce9c5f73ee02)

**Comment by nkuba** [comment]
Designs have changed.
