### ISSUE TITLE
The blur behind different modals is not applied evenly

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#535]
If you open the `Acre&Mezo` modal after scrolling the page down (on 'short' windows), the blur behind the modal gets does not cover the right area:

![image](https://github.com/thesis/acre/assets/78352137/3ea699df-4ff8-4fa8-b4c1-c459ef056de0)

**Comment by kkosiorowska** [comment]
Done in https://github.com/thesis/acre/pull/777
