### ISSUE TITLE
Weird placement of the Beehive banner on narrow screens and with a lot of txs in the history

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#580]
I think the banner would look better if placed higher up, just below the other two banners (not sure how feasible this is).
Here's how this looks right now:

https://github.com/thesis/acre/assets/78352137/d170a29b-4989-4b8b-ae39-6ced4669232b

**Comment by kkosiorowska** [comment]
Done in https://github.com/thesis/acre/pull/763

**Comment by kkosiorowska** [comment]
Done in https://github.com/thesis/acre/pull/763
