### ISSUE TITLE
Truncated element on the 'Not enough funds left...' view on small screens

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#602]
The dark beige banner is truncated on a narrow screen on the 'Not enough funds left...' screen on smaller windows:

<img width="555" alt="image" src="https://github.com/user-attachments/assets/7799017b-00aa-4765-a9b9-175a419c4a55">

**Comment by kkosiorowska** [comment]
Done in https://github.com/thesis/acre/pull/766
