### ISSUE TITLE
dashboard/beehive/ acre&mezo copy > inadvertant text wrap before `mark class` "deposit amount and duration"

### ISSUE THREAD

**Issue by pnicjanik** [thesis/acre#613]
dapp.test.acre.fi/dashboard

1. connect
2. navigate to /dashboard/Beehive
3. click More info
- text displays as:

> In the event of a reward distribution, your share
> will be calculated based on your 
> **deposit amount and duration**. You will be able to
> claim your share directly from **Acre**.

<img width="494" alt="acre_beehive-moreInfo-yourShare_20240717-180509" src="https://github.com/user-attachments/assets/6e47714f-429e-4022-8404-44c2aa836754">

no need to wrap before **deposit**. room for:
> In the event of a reward distribution, your share
> will be calculated based on your **deposit** 
> **amount and duration**. You will be able to
> claim your share directly from **Acre**.

**Comment by kkosiorowska** [comment]
The issue is out of date. The current version of task can be found here https://github.com/thesis/acre/issues/808
