### ISSUE TITLE
staking widget's "view in mempool" arrow doesn't change on hover (always grey)

### ISSUE THREAD

**Issue by pnicjanik** [thesis/acre#622]
https://dapp.test.acre.fi/dashboard

- initiate & complete a deposit
- "Staking..." entry displayed with arrow linking out to mempool ...in gray(...grey?)
- hover over arrow >>> still gray
- for consistency, hovering over should change to orange (as other links out to mempool in transactions list)

(screenshot not very helpful other than to show it's gray)

**Comment by kkosiorowska** [comment]
We will soon update the basic components with style guide. So I think we can close this task, because in the next steps we will unify the styles of links and buttons.
