### ISSUE TITLE
The `You will receive your rewards...` info should be visible only sometimes on the `Awaiting transaction` screen

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#625]
As per [this](https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8?node-id=14807-14054#881058478) Figma comment:

> In the deposit flow.
> Need to make sure we only show this message on first-time deposits or for users who have withdrawn everything and are making a comeback.

![image](https://github.com/user-attachments/assets/9bc5c6a6-d680-469c-bea0-16812b110f59)

When implementing, please remember that stBTC has a different precision than BTC and due to that users who have chosen to withdraw everything via Acre may end up with some dust stBTC still present. We should treat such users as the users with 0 stBTC

**Comment by kkosiorowska** [comment]
The issue is outdated.
