### ISSUE TITLE
Improve formatting of Docs/FAQ/Contracts links

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#631]
As per https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8?node-id=14880-13463#876199571:

![image](https://github.com/user-attachments/assets/73169390-9a81-413c-a27b-68d1e8726e85)

**Comment by kkosiorowska** [comment]
The issue is out of date. Sidebar will be removed - https://github.com/thesis/acre/issues/846
