### ISSUE TITLE
Revise the copy and styling on the 'Acre & Mezo' modal

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#642]
As per https://coda.io/d/Acre_d3Vs1FswTQA/Engin-Erdogan-7-16-2024_suOyt#_lux7j:

>  Change in layout for the popup
>  * Remove the first sentence (Mezo Points are collected from all Acre deposits)
>  * Bring the green box text to the top in the place of removed one. We may no longer need a green box there. 
>  * Revise the text to: Acre users participate in Mezo points program automatically as a group. 
>  * Remove the bubble that has Chain Launch date in it

![image](https://github.com/user-attachments/assets/6091969d-6f8d-458b-908c-0c2d3ff504cc)

**Comment by kkosiorowska** [comment]
Fixed in https://github.com/thesis/acre/pull/766

**Comment by kkosiorowska** [comment]
The issue is out of date. The current version of task can be found here https://github.com/thesis/acre/issues/808
