### ISSUE TITLE
Elements on the page 'jump' when user switches between tabs

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#643]
As per https://coda.io/d/Acre_d3Vs1FswTQA/Engin-Erdogan-7-16-2024_suOyt#_luy4H the dashboard elements move slightly right after user switches between the Season 1 and Dashboard tabs:

https://github.com/user-attachments/assets/e82fe42d-395d-49b6-b8f0-7b8fecc45496

**Comment by kkosiorowska** [comment]
The issue is out of date
