### ISSUE TITLE
Update the `Loading...` view in the deposit/withdrawal flow

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#644]
As per https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8/Web-dApp?node-id=14807-14241&t=KKV5aRKbWZULYxqx-0 and https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8/Web-dApp?node-id=14807-14290&t=KKV5aRKbWZULYxqx-0 we should do a couple of changes to the `Loading...` view:
* rename the window to `Signing...`
* remove skeleton
* remove the `X`
* add a text that would explain that the operation may take some time:
'This process may take up to a minute.
Please don't close this window.'

![image](https://github.com/user-attachments/assets/3e6fa546-f41a-4cf6-8886-464f849dc6a7)

**Comment by kkosiorowska** [comment]
The issue is out of date
