### ISSUE TITLE
unsupported address error sticky when navigating back/forth between dashboard-season1-dashboard

### ISSUE THREAD

**Issue by pnicjanik** [thesis/acre#656]
found during testing of **Improve the logged-out view of the [Dashboard #608](https://github.com/thesis/acre/pull/608)** 

**pre-requisite:** unsupported address type selected in wallet extension (taproot, nested)
* ://dapp.test.acre.fi/ or ://stake.acre.fi/
* navigate to /dashboard ... Connect your wallet modal appears
* click to SIWW >> "not supported" address error displayed ✓
* go to wallet & change to supported addr.type (native, legacy) >> connection modal remains displayed w/ error
* navigate to Season1 (connection modal hidden)
* navigate back to /dashboard >> **connection modal returns, retaining error**
* click applicable wallet to SIWW >> successfully prompted for signing

expected: "fresh" wallet connected modal with no reference to unsupported address
actual: unsupported address error is sticky, retained on navigation from-to despite update in wallet to supported type.

https://github.com/user-attachments/assets/0f75053b-a314-4c12-bb99-ac9d3d48480a

**Comment by kkosiorowska** [comment]
Currently we support only one dashboard page, the season page has been removed. So I think we can close it because the logic has changed a lot since that time.
