### ISSUE TITLE
Errors on the `Select your wallet` window get truncated on small browser windows

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#734]
Errors on the `Select your wallet` window get truncated when users display dapp in small browser windows:

![image](https://github.com/user-attachments/assets/3805a0c4-fe6e-4aec-97b3-2daa9e763afd)

Tested on
https://deploy-preview-731--acre-dapp.netlify.app/
🚀 Network: mainnet
⛓️ Latest commit hash: 9ddbfb8b

**Comment by kkosiorowska** [comment]
Done in https://github.com/thesis/acre/pull/766
