### ISSUE TITLE
[Acre points UI] Acre points balance dashboard component doesn't match figma 

### ISSUE THREAD

**Issue by pnicjanik** [thesis/acre#735]
https://deploy-preview-704--acre-dapp-testnet.netlify.app/
mwp7CjXuQCxSvUu95ZSygHdUFYMr3SZBKh

Per [Figma Dashboard Components > Points](https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8/Web-dApp?node-id=16291-6&node-type=frame&t=ulGGw5dBd70oSHIX-0) ...
* title
   * Expected: **Your** Acre points balance
   * Actual: Acre points balance
* PTS/day
   * Expected: `+#,### PTS/day` displayed between user's points balance & "Next drop in"
   * Actual: `+#,### PTS/day` not displayed
* "Next drop in" text color
   * Expected:  #675E60 (gray)
   * Actual: #231f20 (black)

<img src="https://github.com/user-attachments/assets/a8f1e603-9700-42da-aebb-6b6f9b648afd" width=600>

**Comment by kpyszkowski** [comment]
> Expected: +#,### PTS/day displayed between user's points balance & "Next drop in"

We don't store daily increase amount in database. It bases on deposit amount. We decided to skip it.

**Comment by kkosiorowska** [comment]
> > Expected: +#,### PTS/day displayed between user's points balance & "Next drop in"
> 
> We don't store daily increase amount in database. It's based on deposit amount. We decided to skip it.

@SorinQ So could you update the designs to be consistent with the dApp?

**Comment by SorinQ** [comment]
Who decided to skip it?

**Comment by pnicjanik** [comment]
verified on stake.test.acre.fi:
1) resolved - "Your" added to "Your Acre points balance"
2) skipped - this was descoped; added comment in Figma as designs haven't been updated to match display at launch
3) resolved - verified text color change for "Next drop in" to `675E60`
