### ISSUE TITLE
[Acre points UI] Errors in Deposit modal results in vertical scroll bar

### ISSUE THREAD

**Issue by pnicjanik** [thesis/acre#749]
when an error is thrown in the Deposit modal, and the error message is added, vertical scrolls appears. In some cases, it is displayed when it is not necessary.

https://deploy-preview-704--acre-dapp-testnet.netlify.app/
1. log in
2. click to `Deposit more`

3. NO VALUE= without entering an amount, click to `Deposit` >> error displayed. full content visible, but scroll bar presented.
4. NSF= enter value that exceeds wallet balance, click to `Deposit` >> error displayed. deposit button partially obscured
5. BELOW MIN= enter value that is below minimum required deposit, click to `Deposit` >> error displayed. deposit button partially obscured

This is partially dependent on window/screen size: these tests run at max avail height of 968px.

Because of the variations, suggest either removing the spacing that's causing the scroll to appear when it's unnecessary (3. NO VALUE), or widening the modal to allow for more text per line in the error messages.

https://github.com/user-attachments/assets/268e21b7-b9e2-4e25-b2d0-26e1d8f974f8

**Comment by kpyszkowski** [comment]
@pnicjanik 

Please let me know what do you think about such solution. I made the button sticky to the bottom of the modal so it always remains visible on the screen. 

Also as you might notice there is a slight layout shift as the error message appears, let's cover it later. It's actually much more complex to solve.

https://github.com/user-attachments/assets/9e545de4-175a-4e2a-b5b5-91b60296d053

**Comment by pnicjanik** [comment]
shoulda replied with more than a 🎉, so ... yes! looks great!
