### ISSUE TITLE
Elements proportions & responsiveness

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#757]
Following our conversation on Discord, I’ve created this issue to address the problem with breakpoints and ensure responsiveness, even on the smallest screens.

https://discord.com/channels/1079490158639976609/1290310716620017736

I've put together a sample in Figma to help us with this. 
https://www.figma.com/design/lEtpjDlSQbAAyqwQdnDU0U/Ledger-dApp?node-id=13441-30475

@kkosiorowska Please let me know if anything else is required.

PS. Mobile version is also in progress and will be delivered separately.

**Comment by nkuba** [comment]
@kkosiorowska has this issue been covered by https://github.com/thesis/acre/pull/766?

**Comment by kkosiorowska** [comment]
> @kkosiorowska has this issue been covered by #766?

Yes, so I think we can close this task.
