### ISSUE TITLE
Improve the use of the scrollbar when the modal window is open

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#770]
The sidebar has a dynamically set margin depending on whether the modal window is scrolling. What should be improved:

- When the focus is on the sidebar, scrolling is blocked for the modal window.
- The user has the option to disable the visibility of the scroll bar by the system settings. The extra margin for the sidebar does not look good in that case. Let's check if we can improve it somehow.

More details can be found [here](https://github.com/thesis/acre/pull/766#issuecomment-2417289269).

**Comment by nkuba** [comment]
We're removing the sidebar in https://github.com/thesis/acre/issues/846.
