### ISSUE TITLE
Update the Points Calculator component inside the deposit modal

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#778]
I would like us to improve the design of the points section within the deposit modal.

Main changes:

- Remove the yearly option (our points campaign will not run for an entire year).
- Add a daily option instead to match our daily claim.
- Set Monthly as the first option and make it the default.

Design for reference:
https://www.figma.com/design/lEtpjDlSQbAAyqwQdnDU0U/Ledger-dApp?node-id=14022-2692

**Comment by kpyszkowski** [comment]
Resolved by https://github.com/thesis/acre/pull/785
Closing
