### ISSUE TITLE
Error everytime I open the dApp

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#786]
![Screenshot 2024-10-25 at 16 57 14](https://github.com/user-attachments/assets/19a5ff3b-e0fb-4f40-a9a2-cf13882638ec)

1. Go to Ledger / Discovery
2. Open Acre dApp
3. Connect flow dialogue is displayed automatically
4. Sign message with Ledger
5. - ERROr - 

Workaround
It works always the second time when it requires me to select the BTC acccount as well in the process.

**Comment by Dappsnode** [comment]
@SorinQ You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[ledger Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by nkuba** [comment]
It will be fixed in https://github.com/thesis/acre/pull/780
