### ISSUE TITLE
Display Net Amount in Transactions List

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#794]
As Is: Transaction list currently displays the full amount before fees (e.g., 0.0150).

To Be: Update the transaction list to display the net amount after fees are deducted (i.e., the actual amount deposited).

Acceptance Criteria:

-     Calculate and display the net amount (after fees) in the transaction list.
-     Ensure no rounding issues and that the displayed amount matches the deposited amount accurately.

**Comment by nkuba** [comment]
@SorinQ, we have two types of transactions displayed in the history:
- Deposit
- Withdraw

Each transaction amount corresponds to the change in the user balance.

For Deposit transactions, we display the net amount after the fees that were added to the balance ([tx](https://mempool.space/testnet/tx/79b9a29b37f2fcfc1adb5b267124f90cc5080e08041a90438cd285c4692a6eb2)):
<img width="646" alt="image" src="https://github.com/user-attachments/assets/ec20b322-3a04-4efd-8256-02439913d538">

For Withdraw transactions, we display the gross amount before the fees that were deducted from the user balance ([tx](https://mempool.space/testnet/tx/e8e6b604d9fc23648bd16561b50e92a90d5b64c7ae35a69978f3e2a7d465d250)):
<img width="646" alt="image" src="https://github.com/user-attachments/assets/878934eb-df5e-4578-a605-a277584daf40">


The current behavior matches the expectations from the issue description.
