### ISSUE TITLE
Bug: Disconnect Button Not Functioning

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#800]
Pressing the "Disconnect" button has no effect; it does not disconnect the user as expected.

**Comment by kkosiorowska** [comment]
@SorinQ  Could you please give more details? I tested it for the standalone dApp and it looks like everything works well. 🤔

https://github.com/user-attachments/assets/1ff30eba-112b-43c7-8806-89ae308539ee

**Comment by nkuba** [comment]
The button works.
