### ISSUE TITLE
Add "Gas Fee" Error Logic to Deposit Form

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#819]
As Is: The current Deposit form does not account for errors related to insufficient gas fees, potentially leading to failed transactions without clear feedback for the user.

To Be: Implement new error logic in the Deposit form to handle "Gas Fee" errors, providing users with clear feedback when there are insufficient funds to cover gas fees.

https://www.figma.com/design/Ov4M1oVlSrO4Pl7NmGOHC1/%22Zero%22?node-id=124-15509

**Comment by kkosiorowska** [comment]
Let's close this task because it is a duplicate. The problem should be solved in https://github.com/thesis/acre/issues/537
