### ISSUE TITLE
[UI] [Ledger] Mats Component Text Overflowing Out of the Box

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#849]
<img width="456" alt="Screenshot 2024-11-13 at 11 53 45" src="https://github.com/user-attachments/assets/3c4514a3-0d23-467e-a8e9-c05f07029220">

As Is: The text in the Mats component is overflowing and extending outside the intended layout box, affecting readability and visual consistency.

To Be: Adjust the Mats component layout to ensure that all text remains within the boundaries of the component box, maintaining a clean and readable presentation.

**Comment by nkuba** [comment]
@SorinQ let's retest it after https://github.com/thesis/acre/pull/837 lands.

**Comment by nkuba** [comment]
Fixed in the latest release 
<img width="375" alt="image" src="https://github.com/user-attachments/assets/ab7e0931-4b67-475e-9583-8ee7c582378d">

**Comment by nkuba** [comment]
It looks fine on normal width:
<img width="374" alt="image" src="https://github.com/user-attachments/assets/848f6431-babf-42ba-b181-439e1d452fb7">

But at narrow resolutions, the icon gets detached from the text, while I'd expect it to stick with the `Mezo` text moving to the next line.
<img width="306" alt="image" src="https://github.com/user-attachments/assets/8701df10-4059-4ec4-9117-dbe906df0211">
