### ISSUE TITLE
`Connect account` looks like an active button when the welcome panel is on, despite being inactive

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#857]
When the welcome panel is displayed, the `Connect account` button is not active (clicking on it does not result in any action). Can we somehow convey this inactivity to the user? By graying the button out / blurring etc...

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/8fca6f02-9c2d-4ee4-9b1f-2693b4a8927b">

```[tasklist]
### Tasks
- [ ] Hide the "Connect" button when the Welcome modal is present.
- [ ] Hide X close button for the Welcome modal.
```

**Comment by kpyszkowski** [comment]
Related with https://github.com/thesis/acre/issues/832
Resolving mentioned issue should fix this one as well.
