### ISSUE TITLE
Resets activities state after disconnection

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#861]
The transaction table should be cleaned up when the user disconnects.

**Steps to reproduce:**
1. Connect account
2. Click the "disconnect" button on top (make sure the data is still loading, visible skeleton)

https://github.com/user-attachments/assets/246a3c52-6a6c-445d-b16f-c7b07beebf94

**Comment by nkuba** [comment]
The problem here occurs when you press the disconnect button before the transaction history is loaded. 

When the button is pressed after the history is loaded it is cleared correctly:
https://github.com/user-attachments/assets/877cffd5-6bdf-41aa-9336-ea062f9fa969
