### ISSUE TITLE
 Extend the timeout for checking the transaction result for Gelato

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#866]
While testing withdrawals in the standalone dapp on the testnet preview of PR [#860](https://github.com/thesis/acre/pull/860) I got a Gelato error when depositing:
```
console.js:36 Error: GelatoRelaySDK/getTaskStatus: Failed with error: Status not found
    at index.js:19:15
    at Generator.throw (<anonymous>)
    at ot (index.js:6:57)
```

![image](https://github.com/user-attachments/assets/1627bb4f-224f-4daf-aea2-7e41dfa296d9)

Account: `tb1qxm6txd3ule95xrvlm5ul8q2qh7yw7ugwmfdgz0`.

The error seemed to not affect any functionality - the withdrawal was correctly processed and after few hours was visible as completed in the dapp.

When discussed on [Discord](https://discord.com/channels/1079490158639976609/1305807110948520006/1306687627436490792), @nkuba suggested:

> Maybe we need to extend the timeout for checking the transaction result for Gelato. Please record a ticket for this error

**Comment by kkosiorowska** [comment]
Fix should be done in the [orangekit](https://github.com/thesis/orangekit/blob/main/typescript/sdk/src/lib/utils/relayTransaction.ts) package.
